name: cadvisor
namespace: kube-system
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/cadvisor
  tag: v0.44.0
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 100Mi
    cpu: 100m

port: 10260

# controller.livenessProbe
# Liveness probe configuration
# Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
livenessProbe:
  enabled: true
  failureThreshold: 30
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

# controller.readinessProbe
# Readiness probe configuration
# Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
readinessProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

global:
  podSecurityStandards:
    enforced: false
