name: cadvisor
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/cadvisor
  tag: v0.44.0
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 400Mi
    cpu: 400m
  limits:
    memory: 2000Mi
    cpu: 800m
