checks:
  addAllBuiltIn: true
  exclude:
  - "run-as-non-root"
  - "sensitive-host-mounts"
  - "non-isolated-pod"
  - "required-annotation-email"
  - "required-label-owner"
  - "privilege-escalation-container"
  - "privileged-container"
  - "host-network"
