version: 2.1
orbs:
  architect: giantswarm/architect@4.18.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "package and push cadvisor-app chart"
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "cadvisor-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
