kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "resource.default.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "resource.default.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "resource.default.name" . }}
  namespace: {{ .Values.namespace }}
