{{ if .Capabilities.APIVersions.Has "autoscaling.k8s.io/v1" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Chart.Name }}
      controlledValues: RequestsAndLimits
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name:  {{ include "resource.default.name" . }}
  updatePolicy:
    updateMode: Auto
{{ end }}
